### ISSUE TITLE
Test failures in python:3.8-windowsservercore-1809 container

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#115]
I spent at least 15 hours of my time trying to debug this and have figured out absolutely nothing. There were no code changes between the working and broken state. Installing the exact pip dependency versions it had when it worked didn't fix it. I have no idea what happened.

So I've decided to just disable CI on this specific combination for now, so actual development can happen.

**Comment by duckinator** [comment]
Note to future self: If CI for `python:3.8-windowsservercore-1809` is re-added, make sure to mark it as required under the branch protection rules.

**Comment by duckinator** [comment]
While working on #179, I found a _possible_ cause of the problem: `os_version` is set to 2019, but all the images are based on `windowsservercore-1809`.

**Comment by duckinator** [comment]
Okay, I think I'm going to have to redo the Windows CI tasks to work more like the FreeBSD ones: use the cirrus base image, and install the various Python versions. They only support 1709, 1803, and 2019 -- not 1809.

**Comment by duckinator** [comment]
Turns out 2019 and 1809 are currently the exact same build. Not that that's documented well.

So I have no idea what's up, but I'm close to fixing the problem by using cirrus' base image.

**Comment by nbraud** [comment]
> So I have no idea what's up, but I'm close to fixing the problem by using cirrus' base image.

Looks like that's exactly what you did.
