### ISSUE TITLE
Remove Python 3.5 support.

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#180]
As of today, [Python 3.5 has reached end-of-life](https://devguide.python.org/#status-of-python-branches).

I want to determine a time or condition after which 3.5 support is dropped _but_ I don't want to cause problems for users.

If you're using Emanate and Python 3.5 together, please leave a comment below letting me know what operating system you're using and if something is preventing you from upgrading.

**Comment by duckinator** [comment]
cc @nbraud since a bit over a year ago (#63) you mentioned using emanate on some systems with only Python 3.5.

**Comment by nbraud** [comment]
Oops, sorry for missing this issue.  Yes, I'm fine with dropping support for Py3.5, and even Py3.6.

**Comment by duckinator** [comment]
I want to take a general approach of supporting all versions of Python that haven't reached EOL. So, barring anyone saying they need Py3.6 support for longer (as you did with Py3.5), the current plan is to support Py3.6 [until at least December](https://devguide.python.org/#status-of-python-branches).
