### ISSUE TITLE
fix `author = attr: ...` in setup.cfg

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#236]
as @u1f408 discovered, PyPi disapproves of Emanate's approach to this.

![Screenshot_20210320_011746](https://user-images.githubusercontent.com/39698/111859964-dfb0e800-891a-11eb-91ed-d71665fae153.png)

**Comment by nbraud** [comment]
Oh, PyPI...

**Comment by nbraud** [comment]
I checked, that doesn't seem to be a PyPI thing, and instead it's a `setuptools` things: the metadata is wrong in the build wheel and installed package too:

```py3
>>> from importlib import metadata
>>> metadata.metadata('emanate').get('author')
'attr: emanate.__author__'
```
