### ISSUE TITLE
emanate symlinks files in ignored directories

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#30]
If `emanate.json` contains, say,

```
{"ignore": ["*/venv"]}
```

it will still try to add everything matching `*/venv/*`.

WORKAROUND: Ignore both `"*/venv"` _and_ `"*/venv/*"`, until this is fixed.

**Comment by nbraud** [comment]
Oh, I thought that was on purpose.

**Comment by duckinator** [comment]
nah. i just either hadn't encountered it or hadn't considered it a big enough problem to open an issue about, not sure which lol

**Comment by duckinator** [comment]
This should be resolved by #37/#38. Should probably add an actual test for it.

**Comment by duckinator** [comment]
Turns out, what I mentioned above was only _part_ of why emanate was copying stuff from venv/.

The other part is that it was resolving symlinks first. E.g., it was resolving `venv/bin/python3` to `/usr/bin/python3.7` on some systems and, welp, that's not matched by anything in the ignore list.

**Comment by duckinator** [comment]
Fixed in 6.0.1. Just add "venv" to your ignored list.
