### ISSUE TITLE
emanate's ignored file list requires */ prefix

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#31]
At the moment you have to do:

```
{
  "ignore": ["*/README.md", "*/bootstrap.py", "*/emanate.py", "*/venv", "*/venv/*"]
}
```

Note that every file has to be prefixed with `*/` for emanate to acknowledge it, currently.

@nbraud does having all file matches for ignored files match against "<source dir>/<pattern>" make sense to you?

E.g., `README.md` would match `<source dir>/README.md`, `*/foo` would match `<source dir/*/foo`, etc.

**Comment by nbraud** [comment]
Would `/README.md` match only against `<source dir>/README.md` ?

**Comment by nbraud** [comment]
TBH, at that point I would consider implementing the same semantics as `.gitignore`?

**Comment by duckinator** [comment]
the person who found the bug is interested in contributing, so i'll look into working on this with them. :)

i'm unsure whether to go with gitignore-style paths entirely or not. will have to think on that a bit.

but, if we don't use that library, i'm also in favor of using a subset of the `.gitignore` semantics.
