### ISSUE TITLE
Using CI compute credits

### ISSUE THREAD

**Issue by duckinator** [duckinator/emanate#67]
I just realized that #66 likely won't help because of https://github.com/cirruslabs/cirrus-ci-docs/issues/284.

Hoping to find a workaround sometime soon, because it really sucks when CI gets clogged up due to trying to do 24 things at once. :upside_down_face:

**Comment by nbraud** [comment]
@duckinator This should be solved by Cirrus now, thanks to @fkorotkov  <3

**Comment by duckinator** [comment]
Confirmed that this is in fact fixed. ^^

**Comment by fkorotkov** [comment]
Hooray! 🍾
