### ISSUE TITLE
Option to overwrite existing files

### ISSUE THREAD

**Issue by technillogue** [duckinator/emanate#71]
If another tool left a bunch of broken dotfiles (or if there's a default .profile, etc) emanate should have an option to overwrite them.

**Comment by duckinator** [comment]
So, I had completely forgotten about this feature, but it looks like it's supposed to already do this. :sweat_smile: 

Looking at [`emanate/__init__.py`, line 151](https://github.com/duckinator/emanate/blob/master/emanate/__init__.py#L151), if a file exists, then it should prompt you with:

```
/path/to/destination_file already exists. Replace it? [Y/n]
```

@technillogue is this not happening for you?

If it does that, you should be able to pass `--no-confirm`.

**Comment by duckinator** [comment]
Closing this because I can't reproduce and it's been two months with no response.

@technillogue if you're still having this issue, leave a comment here saying so and I'll re-open it.
